# Site settings
title: โครงการพสวท. และทุนเรียนดี
email: phanchat_n@silpakorn.edu
description: โครงการพสวท. และโครงการเรียนดี ศูนย์มหาวิทยาลัยศิลปากร
url: "http://dpst.sc.su.ac.th" # the base hostname & protocol for your site
#fb_admin:
#fb_publisher:

#twitter:

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
